// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';


var genericError = /* record */[/* message */"Error: An issue occured"];

var notFoundError = /* record */[/* message */"We could not find your .paydayrc file!"];

function isError(str) {
  return str.indexOf("Error:") > -1;
}

function fileNotFound(message) {
  return message.indexOf("no such file or directory") > -1;
}

function checkErrorMessage(message) {
  var match = fileNotFound(message);
  if (match) {
    return notFoundError;
  } else {
    return genericError;
  }
}

exports.genericError = genericError;
exports.notFoundError = notFoundError;
exports.isError = isError;
exports.fileNotFound = fileNotFound;
exports.checkErrorMessage = checkErrorMessage;
/* No side effect */
