// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';


var genericError = /* record */[/* message */"An issue occured"];

var notFoundError = /* record */[/* message */"We could not find your .paydayrc file!"];

function fileNotFound(message) {
  return +(message.indexOf("no such file or directory") > -1);
}

function checkErrorMessage(message) {
  var match = fileNotFound(message);
  if (match !== 0) {
    return notFoundError;
  } else {
    return genericError;
  }
}

exports.genericError      = genericError;
exports.notFoundError     = notFoundError;
exports.fileNotFound      = fileNotFound;
exports.checkErrorMessage = checkErrorMessage;
/* No side effect */
