// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var DateUtil     = require("./DateUtil.js");
var KeyValueFile = require("./KeyValueFile.js");

var today = new Date();

var currentYear = today.getUTCFullYear();

function daysUntilPayday(param, today) {
  var payday = param[/* value */1];
  var numToday = DateUtil.numDayOfDate(today);
  var numDays = payday - numToday;
  var days = numDays > 0.0 ? numDays : payday + DateUtil.daysLeftInMonth(numToday, DateUtil.daysInMonth(currentYear, DateUtil.monthOfDate(today)));
  var outputDays = days | 0;
  return "There are " + (String(outputDays) + " days until payday");
}

var outputString = daysUntilPayday(KeyValueFile.paydayValue(/* () */0), today);

console.log(outputString);

exports.today           = today;
exports.currentYear     = currentYear;
exports.daysUntilPayday = daysUntilPayday;
exports.outputString    = outputString;
/* today Not a pure module */
