// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var DateUtil     = require("./DateUtil.js");
var KeyValueFile = require("./KeyValueFile.js");

var today = new Date();

var currentYear = today.getUTCFullYear();

function daysUntilPayday(payday, today) {
  var numToday = DateUtil.numDayOfDate(today);
  var numDays = payday - numToday;
  var days = numDays > 0.0 ? numDays : DateUtil.daysLeftInMonth(numToday, DateUtil.daysInMonth(currentYear, DateUtil.monthOfDate(today))) + payday;
  var outputDays = days | 0;
  return "There are " + (String(outputDays) + " days until payday");
}

var result = KeyValueFile.paydayFromFile(/* () */0);

var match = KeyValueFile.desiredContent(result);

var outputString = match !== 0 ? daysUntilPayday(KeyValueFile.paydayValue(result), today) : result;

console.log(outputString);

exports.today           = today;
exports.currentYear     = currentYear;
exports.daysUntilPayday = daysUntilPayday;
exports.result          = result;
exports.outputString    = outputString;
/* today Not a pure module */
