// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Fs          = require("fs");
var $$Error     = require("./Error.js");
var Js_exn      = require("bs-platform/lib/js/js_exn.js");
var Process     = require("process");
var Caml_array  = require("bs-platform/lib/js/caml_array.js");
var Caml_format = require("bs-platform/lib/js/caml_format.js");

var match = Process.env["HOME"];

var home = match !== undefined ? match : "";

var configPath = "" + (String(home) + "/.paydayrc");

function desiredContent(message) {
  return +(message.indexOf("PAYDAY_DATE") > -1);
}

function paydayValue(paydayFile) {
  return Caml_format.caml_float_of_string(Caml_array.caml_array_get(paydayFile.split("="), 1));
}

function paydayFromFile() {
  try {
    return Fs.readFileSync(configPath, "utf8");
  }
  catch (raw_exn){
    var exn = Js_exn.internalToOCamlException(raw_exn);
    if (exn[0] === Js_exn.$$Error) {
      var match = exn[1].message;
      if (match !== undefined) {
        return $$Error.checkErrorMessage(match)[/* message */0];
      } else {
        return $$Error.genericError[/* message */0];
      }
    } else {
      throw exn;
    }
  }
}

exports.home           = home;
exports.configPath     = configPath;
exports.desiredContent = desiredContent;
exports.paydayValue    = paydayValue;
exports.paydayFromFile = paydayFromFile;
/* match Not a pure module */
