// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");
var Util$GearUtil = require("./Util.bs.js");

function print(label, value) {
  console.log("" + (String(label) + (": " + (String(value) + ""))));
  return /* () */0;
}

console.log("Hello, welcome to GearUtil!");

print("Cadence", Pervasives.string_of_float(90.0));

print("Development", Pervasives.string_of_float(6.2));

print("Wheel Diameter", Pervasives.string_of_float(26.38));

print("Chainring", Pervasives.string_of_float(46));

print("Cog", Pervasives.string_of_float(16));

print("Crank Length", Pervasives.string_of_float(165));

console.log("===========================================");

print("Cadence and metres of development to km/hr", Pervasives.string_of_float(Util$GearUtil.cadenceToSpeedKm(90.0, 6.2)));

print("Cadence and metres of development to mi/hr", Pervasives.string_of_float(Util$GearUtil.cadenceToSpeedMiles(90.0, 6.2)));

print("Gear inches", Pervasives.string_of_float(Util$GearUtil.gearInches(26.38, 46, 16)));

print("Greatest common divisor of 54 and 24", Pervasives.string_of_float(Util$GearUtil.greatestCommonDivisor(54, 24)));

var fraction = Util$GearUtil.lowestFraction(64, 22);

print("Lowest fraction of 64/22", "" + (String(fraction) + ""));

print("Metres of development", Pervasives.string_of_float(Util$GearUtil.metresOfDevelopment(26.38, 46, 16)));

print("Skid patches", Pervasives.string_of_float(Util$GearUtil.skidPatches(46, 16)));

print("Ambidextrous skid patches", Pervasives.string_of_float(Util$GearUtil.skidPatches(46, 17.0)));

print("Gain ratio", Pervasives.string_of_float(Util$GearUtil.gainRatio(26.38, 165, 46, 16)));

print("Equivalent gears", List.map((function (param) {
            return " " + (String(param[/* numerator */0]) + ("/" + (String(param[/* denominator */1]) + "")));
          }), Util$GearUtil.equivalentGear(46, 16, Belt_Array.range(1, 100))));

var cadence = 90.0;

var development = 6.2;

var wheelDiameter = 26.38;

var chainring = 46;

var cog = 16;

var crank = 165;

exports.cadence = cadence;
exports.development = development;
exports.wheelDiameter = wheelDiameter;
exports.chainring = chainring;
exports.cog = cog;
exports.crank = crank;
exports.print = print;
/*  Not a pure module */
