// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';

var Pervasives = require("bs-platform/lib/js/pervasives.js");
var GearUtil$GearUtil = require("./GearUtil.bs.js");

console.log("Hello, welcome to GearUtil!");

console.log("Cadence: " + (Pervasives.string_of_float(90.0) + (", Development: " + Pervasives.string_of_float(6.2))));

console.log("Cadence and metres of development to km/hr: " + Pervasives.string_of_float(GearUtil$GearUtil.cadenceToSpeedKm(90.0, 6.2)));

console.log("Cadence and metres of development to mi/hr: " + Pervasives.string_of_float(GearUtil$GearUtil.cadenceToSpeedMiles(90.0, 6.2)));

var cadence = 90.0;

var development = 6.2;

exports.cadence = cadence;
exports.development = development;
/*  Not a pure module */
