// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';


var mm = /* record */[
  /* mm */1,
  /* cm */1000,
  /* inch */0.0393701,
  /* metre */100.0,
  /* km */100000,
  /* mile */160934
];

var cm = /* record */[
  /* mm */1000,
  /* cm */1,
  /* inch */0.393701,
  /* metre */100.0,
  /* km */100000,
  /* mile */160934
];

var inch = /* record */[
  /* mm */254,
  /* cm */2.54,
  /* inch */1,
  /* metre */0.0254,
  /* km */0.0000254,
  /* mile */0.000015783
];

var metre = /* record */[
  /* mm */1000.0,
  /* cm */100.0,
  /* inch */39.3701,
  /* metre */1.0,
  /* km */0.001,
  /* mile */0.000621371
];

var km = /* record */[
  /* mm */100000.0,
  /* cm */100000.0,
  /* inch */39370.1,
  /* metre */0.0001,
  /* km */1.0,
  /* mile */0.62137
];

var mile = /* record */[
  /* mm */1609040,
  /* cm */160904.0,
  /* inch */63360,
  /* metre */1609.04,
  /* km */1.60904,
  /* mile */1.0
];

function convertTarget(conversion, target, unit) {
  switch (target) {
    case 0 : 
        return unit * conversion[/* mm */0];
    case 1 : 
        return unit * conversion[/* cm */1];
    case 2 : 
        return unit * conversion[/* inch */2];
    case 3 : 
        return unit * conversion[/* metre */3];
    case 4 : 
        return unit * conversion[/* km */4];
    case 5 : 
        return unit * conversion[/* mile */5];
    
  }
}

function convert(base, target, unit) {
  var tmp;
  switch (base) {
    case 0 : 
        tmp = mm;
        break;
    case 1 : 
        tmp = cm;
        break;
    case 2 : 
        tmp = inch;
        break;
    case 3 : 
        tmp = metre;
        break;
    case 4 : 
        tmp = km;
        break;
    case 5 : 
        tmp = mile;
        break;
    
  }
  return convertTarget(tmp, target, unit);
}

var Distance = /* module */[
  /* mm */mm,
  /* cm */cm,
  /* inch */inch,
  /* metre */metre,
  /* km */km,
  /* mile */mile,
  /* convertTarget */convertTarget,
  /* convert */convert
];

var second = /* record */[
  /* second */3600.0,
  /* minute */60,
  /* hour */1,
  /* day */0.0416667,
  /* week */0.00595238571429,
  /* year */0.0001141553424658356045
];

var minute = /* record */[
  /* second */3600.0,
  /* minute */1,
  /* hour */60,
  /* day */0.0416667,
  /* week */0.00595238571429,
  /* year */0.0001141553424658356045
];

var hour = /* record */[
  /* second */3600.0,
  /* minute */60,
  /* hour */1,
  /* day */0.0416667,
  /* week */0.00595238571429,
  /* year */0.0001141553424658356045
];

var day = /* record */[
  /* second */3600.0,
  /* minute */60,
  /* hour */1,
  /* day */0.0416667,
  /* week */0.00595238571429,
  /* year */0.0001141553424658356045
];

var week = /* record */[
  /* second */3600.0,
  /* minute */60,
  /* hour */1,
  /* day */0.0416667,
  /* week */0.00595238571429,
  /* year */0.0001141553424658356045
];

var year = /* record */[
  /* second */3600.0,
  /* minute */60,
  /* hour */1,
  /* day */0.0416667,
  /* week */0.00595238571429,
  /* year */0.0001141553424658356045
];

function convertTarget$1(conversion, target, unit) {
  switch (target) {
    case 0 : 
        return unit * conversion[/* year */5];
    case 1 : 
        return unit * conversion[/* day */3];
    case 2 : 
        return unit * conversion[/* week */4];
    case 3 : 
        return unit * conversion[/* hour */2];
    case 4 : 
        return unit * conversion[/* minute */1];
    case 5 : 
        return unit * conversion[/* second */0];
    
  }
}

function convert$1(base, target, unit) {
  var tmp;
  switch (base) {
    case 0 : 
        tmp = year;
        break;
    case 1 : 
        tmp = day;
        break;
    case 2 : 
        tmp = week;
        break;
    case 3 : 
        tmp = hour;
        break;
    case 4 : 
        tmp = minute;
        break;
    case 5 : 
        tmp = second;
        break;
    
  }
  return convertTarget$1(tmp, target, unit);
}

var Time_005 = /* month : record */[
  /* second */3600.0,
  /* minute */60,
  /* hour */1,
  /* day */0.0416667,
  /* week */0.00595238571429,
  /* year */0.0001141553424658356045
];

var Time = /* module */[
  /* second */second,
  /* minute */minute,
  /* hour */hour,
  /* day */day,
  /* week */week,
  Time_005,
  /* year */year,
  /* convertTarget */convertTarget$1,
  /* convert */convert$1
];

exports.Distance = Distance;
exports.Time = Time;
/* No side effect */
