// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';


var metre = /* float array */[
  1.0,
  0.001,
  0.000621371,
  100.0,
  39.3701
];

var km = /* float array */[
  0.0001,
  1.0,
  0.62137,
  100000.0,
  39370.1
];

var mile = /* float array */[
  1609.04,
  1.60904,
  1.0,
  160904.0,
  63360
];

var cm = /* float array */[
  100.0,
  100000,
  160934,
  1,
  0.393701
];

var inch = /* float array */[
  0.0254,
  0.0000254,
  0.000015783,
  2.54,
  1
];

function convertTarget(conversion, target, unit) {
  switch (target) {
    case 0 : 
        return unit * conversion[/* metre */0];
    case 1 : 
        return unit * conversion[/* km */1];
    case 2 : 
        return unit * conversion[/* mile */2];
    case 3 : 
        return unit * conversion[/* cm */3];
    case 4 : 
        return unit * conversion[/* inch */4];
    
  }
}

function convert(base, target, unit) {
  var tmp;
  switch (base) {
    case 0 : 
        tmp = metre;
        break;
    case 1 : 
        tmp = km;
        break;
    case 2 : 
        tmp = mile;
        break;
    case 3 : 
        tmp = cm;
        break;
    case 4 : 
        tmp = inch;
        break;
    
  }
  return convertTarget(tmp, target, unit);
}

var Distance = /* module */[
  /* metre */metre,
  /* km */km,
  /* mile */mile,
  /* cm */cm,
  /* inch */inch,
  /* convertTarget */convertTarget,
  /* convert */convert
];

var second = /* float array */[
  3600.0,
  60,
  1,
  0.0416667,
  0.00595238571429,
  0.0001141553424658356045
];

var minute = /* float array */[
  3600.0,
  1,
  60,
  0.0416667,
  0.00595238571429,
  0.0001141553424658356045
];

var hour = /* float array */[
  3600.0,
  60,
  1,
  0.0416667,
  0.00595238571429,
  0.0001141553424658356045
];

var day = /* float array */[
  3600.0,
  60,
  1,
  0.0416667,
  0.00595238571429,
  0.0001141553424658356045
];

var week = /* float array */[
  3600.0,
  60,
  1,
  0.0416667,
  0.00595238571429,
  0.0001141553424658356045
];

var year = /* float array */[
  3600.0,
  60,
  1,
  0.0416667,
  0.00595238571429,
  0.0001141553424658356045
];

function convertTarget$1(conversion, target, unit) {
  switch (target) {
    case 0 : 
        return unit * conversion[/* year */5];
    case 1 : 
        return unit * conversion[/* day */3];
    case 2 : 
        return unit * conversion[/* week */4];
    case 3 : 
        return unit * conversion[/* hour */2];
    case 4 : 
        return unit * conversion[/* minute */1];
    case 5 : 
        return unit * conversion[/* second */0];
    
  }
}

function convert$1(base, target, unit) {
  var tmp;
  switch (base) {
    case 0 : 
        tmp = year;
        break;
    case 1 : 
        tmp = day;
        break;
    case 2 : 
        tmp = week;
        break;
    case 3 : 
        tmp = hour;
        break;
    case 4 : 
        tmp = minute;
        break;
    case 5 : 
        tmp = second;
        break;
    
  }
  return convertTarget$1(tmp, target, unit);
}

var Time_005 = /* month : float array */[
  3600.0,
  60,
  1,
  0.0416667,
  0.00595238571429,
  0.0001141553424658356045
];

var Time = /* module */[
  /* second */second,
  /* minute */minute,
  /* hour */hour,
  /* day */day,
  /* week */week,
  Time_005,
  /* year */year,
  /* convertTarget */convertTarget$1,
  /* convert */convert$1
];

exports.Distance = Distance;
exports.Time = Time;
/* No side effect */
